from typing import List, Optional
from datetime import date

# Base class for all members
class Person:
    def __init__(self, name: str, dob: date, contact: Optional[str] = None) -> None: ...
    def get_age(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

# Student class
class Student(Person):
    def __init__(self, name: str, dob: date, admit_id: str, grade: str) -> None: ...
    def calculate_fees(self) -> float: ...
    def __str__(self) -> str: ...

# Teacher class
class Teacher(Person):
    def __init__(self, name: str, dob: date, employee_id: str, subject: str, salary: float) -> None: ...
    def get_salary(self) -> float: ...
    def assign_subject(self, subject: str) -> None: ...
    def __str__(self) -> str: ...

# Non-Teaching Staff class
class NonTeachingStaff(Person):
    def __init__(self, name: str, dob: date, employee_id: str, role: str, salary: float) -> None: ...
    def get_salary(self) -> float: ...
    def assign_role(self, role: str) -> None: ...
    def __str__(self) -> str: ...

# Utility functions
def create_student(name: str, dob: date, admit_id: str, grade: str) -> Student: ...
def create_teacher(name: str, dob: date, employee_id: str, subject: str, salary: float) -> Teacher: ...
def create_non_teaching_staff(name: str, dob: date, employee_id: str, role: str, salary: float) -> NonTeachingStaff: ...
